---
- name: install nginx repo
  tags: nginx
  yum:
    name: http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
    state: present

- name: install nginx
  tags: nginx
  yum: pkg={{ item }} state=latest
  loop:
    - nginx

- name: start nginx
  tags: nginx
  service:
    name: nginx
    enabled: yes
    state: started

- name: copy config files
  tags: nginx
  copy:
    src: "{{ item.src }}"
    dest: "/etc/nginx/{{ item.dest }}"
    owner: nginx
    group: nginx
    mode: 0644
  loop:
    - { src: roles/nginx/files/nginx.conf, dest: nginx.conf }
  notify: nginx configtest

- name: create directory
  tags: nginx
  file:
    path: "/var/www/html/{{ item }}/html/"
    owner: nginx
    group: nginx
    mode: '0775'
    state: directory
    recurse: yes
  with_items:
    - "{{ virtualdomain }}"

#- name: copy virutal config
#  tags: nginx
#  template:
#    owner: nginx
#    group: nginx
#    mode: 0644
#    src: roles/nginx/templates/virtual.conf.j2
#    dest: "/etc/nginx/conf.d/{{ item.dest }}.conf"
#  loop:
#    - { dest:  }
#  notify: nginx configtest
