---
- name: install basic packages
  tags: base
  yum:  pkg={{ item }} state=latest
  loop:
    - git
    - mailx
    - unzip
    - tcpdump
    - telnet
    - wget
    - zsh

- name: useradd
  tags: base
  user:
    name: "{{ ssh_user }}"
    groups: wheel
    shell: /bin/zsh
